packages:
  # Currently unused block, hopefully supported in the future
  - pkg:/developer/gcc51
  - omniti/runtime/erlang@19.0.0
  - pkg:/archiver/gnu-tar
  - pkg:/system/header

environment:
    FOO: BAR
    CC: gcc
    CXX: /usr/bin/g++


stages:
  - name: build
    steps:
      - env
      - pwd
      - make deps app
      - make package

  - name: publish
    match: "^master$"
    steps:
      - make publish
