environment:
    FOO: BAR

stages:
  - name: build
    steps:
      - env
      - pwd
      - make deps app

  - name: package
    match: "^master$"
    steps:
      - make package
      - make publish
