environment:
    FOO: BAR

stages:
  - name: build
    steps:
      - env
      - pwd
      - make deps app
      - make package

  - name: publish
    match: "^master$"
    steps:
      - make publish
