environment:
  CC: gcc
  CXX: "/usr/bin/g++ -m64"
  PATH: /usr/gnu/bin:/opt/omni/bin/:/opt/gcc-5.1.0/bin:$PATH

stages:
  - name: package
    steps:
      - env
      - pwd

      - make -j 4 deps app

      - make package
      - make publish
