environment:
  CC: gcc
  CXX: "/usr/bin/g++ -m64"
  PATH: /usr/gnu/bin:/opt/omni/bin/:/opt/gcc-5.1.0/bin:$PATH

stages:
  - name: build
    steps:
      - pwd
      - make deps app

  - name: package
    match: "^master$"
    steps:
      - make package
      - make publish
