environment:
  CC: gcc
  CXX: "/usr/bin/g++ -m64"
  PATH: /usr/gnu/bin:/opt/omni/bin/:/opt/gcc-5.1.0/bin:$PATH

stages:
  - name: package
    steps:
      - env
      - pwd

      # Need to `make` twice to deal with build ordering in templates https://github.com/ninenines/erlang.mk/issues/457
      - make -j 4 app
      - touch templates/*
      - make app

      - make package
      - make publish
